version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Root directory of your project
    schedule:
      interval: "weekly" # Choose between daily, weekly, or monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "gradle"
    reviewers:
      - "joaoh4547" # Replace with GitHub team or username
    assignees:
      - "joaoh4547" # Replace with the desired GitHub username
